name: Daily Weather Push

on:
  # 1. 定时触发
  schedule:
    # GitHub Actions 使用 UTC 时间
    # 北京时间 06:00 = UTC 时间 22:00 (前一天)
    # 所以设置每天 UTC 22:00 运行
    - cron: '0 22 * * *'
  
  # 2. 手动触发 (方便测试)
  workflow_dispatch:

jobs:
  send-weather:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code (拉取代码)
      uses: actions/checkout@v3
      
    - name: Set up Python (设置 Python 环境)
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies (安装依赖)
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run script (运行脚本)
      env:
        # 将 GitHub Secrets 注入为环境变量
        OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
        WECOM_KEY: ${{ secrets.WECOM_KEY }}
      run: python daily_weather.py
